####regester user
post http://localhost:4100/user/register
Content-Type: application/json

{
    "user_name": "diana",
    "email":"dianaaberi12@gmail.com",
    "password": "@Santa2023"
}

#####get all users

get http://localhost:4100/user
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiIyZjQ0ZGM5Yi1hYjg2LTRhMmItOTg4OS1iM2NkOTVhZTM4MGYiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzAxMzMxOTQ4LCJleHAiOjE3MDE0MTgzNDh9.xT1C8qp8_i-6o00oGerRfTTbhdSI9iR0iw3zJY9K-HY

#####get one user by id
get http://localhost:4100/user/28e61f6e-e838-41c7-a155-380a84d78871
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGViLmJhcmFrYUB0aGVqaXR1LmNvbSIsImlkIjoiMjhlNjFmNmUtZTgzOC00MWM3LWExNTUtMzgwYTg0ZDc4ODcxIiwiaWF0IjoxNzAwOTk0NTc1LCJleHAiOjE3MDEwODA5NzV9.-LbWQugUV9a0G3Uk5OAZBN3HGbijJU-R9XxsxSImIoY

####login user

post http://localhost:4100/user/login
Content-Type: application/json

{    
    "email":"dianaaberi12@gmail.com",
    "password": "@Santa2023"
}
#####update user

put http://localhost:4100/user
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGViLmJhcmFrYUB0aGVqaXR1LmNvbSIsImlkIjoiMjhlNjFmNmUtZTgzOC00MWM3LWExNTUtMzgwYTg0ZDc4ODcxIiwiaWF0IjoxNzAwOTk0NTc1LCJleHAiOjE3MDEwODA5NzV9.-LbWQugUV9a0G3Uk5OAZBN3HGbijJU-R9XxsxSImIoY
Content-Type: application/json

{
    
    "user_id":"28e61f6e-e838-41c7-a155-380a84d78871",
    "user_name": "caleb",
    "email":"baraka606@student.mmarau.ac.ke"
}


##### delete user by ID
delete http://localhost:4100/user/28e61f6e-e838-41c7-a155-380a84d78871
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGViLmJhcmFrYUB0aGVqaXR1LmNvbSIsImlkIjoiMjhlNjFmNmUtZTgzOC00MWM3LWExNTUtMzgwYTg0ZDc4ODcxIiwiaWF0IjoxNzAwOTk0NTc1LCJleHAiOjE3MDEwODA5NzV9.-LbWQugUV9a0G3Uk5OAZBN3HGbijJU-R9XxsxSImIoY

### check user details
get http://localhost:4100/user/check_user_details
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJqb25hdGhhbiIsImVtYWlsIjoiY2FsZWIuYmFyYWthQHRoZWppdHUuY29tIiwidXNlcl9pZCI6IjQ2Njc4MmZiLWZlYTMtNGQxYS05OTgwLTljMTUwMTA1OTYyZSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDA5OTY5MjYsImV4cCI6MTcwMTA4MzMyNn0.5qaeqGuj6Z8CJXU6M5-83jMFbmc5Nyem4vedUHughIo

#### forgot password
post http://localhost:4100/user/forgot
Content-Type: application/json

{
    "email":"caleb.baraka@thejitu.com"
}

##### reset password
post http://localhost:4100/user/reset
Content-Type: application/json

{
    "user_id" : "466782fb-fea3-4d1a-9980-9c150105962e",
    "password" : "@Qwerty123"
}


